train:
  batch_size: 16
  epochs: 5
  log_interval: 100
  generator_lr: 1e-4
  discriminator_lr: 1e-5
  num_workers: 4

  # for continuing training
  load_checkpoint: # change from None to checkpoint path to continue training
  more_epochs: 20 # How many more epochs to train

logger:
  checkpoint_path: "checkpoints/"
  chart_path: "tmp/"

system:
  device: "cuda:0"
  seed: 23

data:
  channels: 1
  size: 1000

discriminator:
  n_layers: 1
  n_channel: 1
  kernel_size: 8
  dropout: 0.0

generator:
  noise_size: 100
  beta: 0.5
  n_layers: 1
  hidden_dim: 256

project: "ECG TGAN"
run_date: ${now:%Y_%m_%d_%H_%M}
run_name: "ECG_TGAN_${run_date}"
