train:
  batch_size: 16
  epochs: 2
  log_interval: 100
  lr: 2e-4
  num_workers: 4

logger:
  checkpoint_path: "checkpoints/"
  chart_path: "tmp/"

system:
  device: "cuda:0"
  seed: 23

data:
  channels: 1
  size: 1000

project: "ECG GAN"
run_date: ${now:%Y_%m_%d_%H_%M}
run_name: "ECG_GAN_${run_date}"
