train:
  batch_size: 16
  epochs: 2
  log_interval: 100
  lr: 2e-4
  num_workers: 4

logger:
  checkpoint_path: "checkpoints/"
  chart_path: "tmp/"

system:
  device: "cuda:0"
  seed: 23

data:
  channels: 1
  size: 1000

model:
  # Structure/Architecture
  output_features_filters: 1
  augment_output_features: False
  input_features_filters: 1  # Aligned with the number of channels
  augment_input_features: False
  output_features_dim: 1000  # Features size post decoding
  input_features_dim: 1000  # Aligned with the number of data points in each channel
  input_features_type: 'mfcc'
  # Encoder-Decoder details
  num_hiddens: 128
  num_residual_layers: 2
  num_residual_hiddens: 16
  use_kaiming_normal: True
  # VQ details
  embedding_dim: 100 # We might want to lower this value in the future, size of embedding vectors
  num_embeddings: 64 # K, needs empirical tuning
  commitment_cost: 0.25
  decay: 0.99
  # Misc
  record_codebook_stats: False
  verbose: False

project: "ECG GAN"
run_date: ${now:%Y_%m_%d_%H_%M}
run_name: "ECG_GAN_${run_date}"
